### ISSUE TITLE
*P1* Remove Cars / Trucks from Submit Free Listing Button/Replace Pic on Home Sceen 

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#19]
![can-am-maverick-x-turbo-side-by-side-11](https://user-images.githubusercontent.com/34143768/37114006-ee7558be-21fb-11e8-8070-9d7490d30e0d.jpeg)
<img width="1440" alt="homescreenpicchange" src="https://user-images.githubusercontent.com/34143768/37114007-ee9cb5bc-21fb-11e8-83aa-57f05ccfb8b7.png">
![quicklistingtoolchange](https://user-images.githubusercontent.com/34143768/37114008-eeb84994-21fb-11e8-9e8c-ef3c6fde5b88.jpeg)

1) Please remove the cars on the scrolling home image (image provided)
2) Please remove the cars/truck image selection on Submit quick listing Button
3) Please replace cars/trucks image with can-am maverick will send on slack as well..

**Comment by urentmellc** [comment]
please ensure resolution is good on image replacement or I will send another one

**Comment by urentmellc** [comment]
![rzr-turbo-168](https://user-images.githubusercontent.com/34143768/37114634-bb3115c2-21fd-11e8-8180-3cffa33823dd.jpg)

please use this photo to replace cars and trucks image

**Comment by pxlsz** [comment]
Done.

**Comment by urentmellc** [comment]
Good morning, checked this is not complete. The cars/trucks is still showing on the submit listing button and the picture still needs to be replaced with the latest one sent to you. Rzr one that’s 4mg. 
		
		

		Get Outlook for iOS
	




On Wed, Mar 7, 2018 at 10:55 PM -0800, "pxlsz" <notifications@github.com> wrote:












Done.

**Comment by Jayantapixel** [comment]
Clear your browser cache and check. Please find attached screenshot what we are getting.
![scrnshot](https://user-images.githubusercontent.com/35031627/37138462-2532c3e4-22d0-11e8-9f82-a10114644c0e.png)

**Comment by urentmellc** [comment]
![errorsubmitlisting](https://user-images.githubusercontent.com/34143768/37165123-b6eea2a0-22b0-11e8-8ae6-d0f5e5973254.jpeg)

remove the picture in the submit free listing... already has utv in red on the bottom, we dont do cars and trucks! Please fix this asap

**Comment by urentmellc** [comment]
Please remove the Cars/Trucks Icon from the Submit Quick Listing which I showed you Jayanta then I can close issue.

**Comment by pxlsz** [comment]
We have removed the Cars/Trucks Icon from the Submit Quick Listing.
