### ISSUE TITLE
~Adding a New Listing for any User in Back End~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#78]
****Several issues with this that need fixing..
1-when hovering over plus now it says "Item add for User", it must say "Enter New Listing".
2-i am unable to add any photos to this it must have this capability for entering a new listing i want it all in one area**
3-I am unable to enter in any make and model it wont let me add a make and model like the site and app. You need to allow it to add any make, or model for any listing.** 

List any Item for Any User in the Admin Panel- I require the immediate need to create, edit, upload, change any listing for any user on our site/platform. This flow would allow myself to easily manage this through the back end via Item Management or a new tab in the admin panel for just that purpose.

<img width="1440" alt="screen shot 2018-05-30 at 6 08 42 am" src="https://user-images.githubusercontent.com/34143768/40719276-5c296358-63d0-11e8-8936-2d7e62d806ec.png">

**Comment by urentmellc** [comment]
You need to be able to upload as many images as i need to place it there to make it easy for me. Also address other issues i have stated.

**Comment by Jayantapixel** [comment]
Regarding point 3, its a major change and we need to estimate the effort & time and send you, if you really want that.  

The add functionality of make and mode is already there in the admin site separately. So if you want, you can add from there and then add item. But in public site, they don't have option to add make/model separately so its there in the add listing form itself.

Please confirm.

**Comment by pixelphpdev** [comment]
We have done following points in admin panel. Please check it. 
1-when hovering over plus now it says "Item add for User", it must say "Enter New Listing".
2-i am unable to add any photos to this it must have this capability for entering a new listing i want it all in one area

**Comment by urentmellc** [comment]
the second point adding a photo to listing does not work see screenshot attached you need to fix this so I can add a photo go check yourself and fix it and let me know when I works correctly and I will test again. 

<img width="1440" alt="screen shot 2018-05-31 at 7 14 36 am" src="https://user-images.githubusercontent.com/34143768/40784253-5c791f9c-64a2-11e8-9618-7bf05e05ea7f.png">

**Comment by urentmellc** [comment]
fix the photo issue so i can approve it to go live. Once I test it and it works we can move it live

**Comment by pixelphpdev** [comment]
We already implanted this and we have checked, it is working properly from our end. Please heard refresh your browser and check again.

**Comment by urentmellc** [comment]
it works push it to live now do not distrupt any database or mess up anything else. Thanks.

**Comment by pixelphpdev** [comment]
We have pushed in live site and item is added from backend. Please check it.

**Comment by urentmellc** [comment]
I did however the photo functionality is still wrong and doesnt work. Please Fix it the way it worked in dev. See screenshot and check yourself. Thank you.

**Comment by urentmellc** [comment]
ok, so in the dev server it works but in live it doesn't... Just this kind of work is why i am getting tired of these mistakes.... Fix it right now...
<img width="1440" alt="screen shot 2018-06-02 at 9 37 33 am" src="https://user-images.githubusercontent.com/34143768/40878077-e4bf8b1e-6648-11e8-8378-ce61357a7e65.png">

**Comment by Jayantapixel** [comment]
There is NO mistakes at all. Please find attached screenshot of live server. We have added one new items (kept deactivated) and images. Its working fine. Before putting harsh word, kindly do twice after **clearing browser cache**. Otherwise do it by a professional tester so we can save our time. Developer also loosing patience with your wrong comments most of the time after your testing specially on website where he has done good job on every occasion. He is a senior guy and handling lot more complected and big projects than yours. We are investing double time for testing due to this.

Kindly test once again and confirm at the earliest. Check live admin panel where we have uploaded an item few hours back without any issue.

![u rent me](https://user-images.githubusercontent.com/35031627/40885254-98b7120c-6740-11e8-9424-4b22909db2ef.png)
![u rent me item list](https://user-images.githubusercontent.com/35031627/40885257-a53b543e-6740-11e8-8a96-e639eae2b2d3.png)
![u rent me item image](https://user-images.githubusercontent.com/35031627/40885260-af5bf0b8-6740-11e8-96e3-a599c741d9e6.png)

**Comment by Jayantapixel** [comment]
This is live last week so please close it.
